name: flutter_map_marker_cluster
description: A Dart implementation of Leaflet.makercluster for Flutter apps.
  Provides beautiful animated marker clustering functionality for flutter_map.
version: 1.3.1

homepage: https://github.com/lpongetti/flutter_map_marker_cluster

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map:
    git:
      url: https://github.com/mootw/flutter_map
      ref: master
  flutter_map_marker_popup: ^6.1.2
  latlong2: ^0.9.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
